name: Build docker image

on:
  push:
    paths:
      - 'fastdeploy_recipe/requirements.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./fastdeploy_recipe/
        file: ./fastdeploy_recipe/fastDeploy.auto_dockerfile
        push: true
        tags: ghcr.io/notai-tech/nudenet:latest
